version: '2'

services:
  player:
    container_name: player
    image: "arupiot/gopd-audio-play:latest"
    privileged: true
    volumes:
       - /opt/audio:/opt/audio
       - /dev/vchiq:/dev/vchiq
       - /opt/vc:/opt/vc
    restart: always
    environment:
      - AUDIO_VOLUME=-900
      - AUDIO_DEVICE=alsa
      - AUDIO_PATH=/opt/audio/test
      - AUDIO_EXT=.mp3
      - AUDIO_LAYOUT=2.1